repos:
    -   repo: https://github.com/python/black
        rev: 23.3.0
        hooks:
            -   id: black
                types_or: [ python, pyi ]
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.1.0
        hooks:
            -   id: trailing-whitespace
            -   id: check-yaml
            -   id: check-added-large-files
            -   id: debug-statements
            -   id: end-of-file-fixer

    -   repo: https://github.com/asottile/reorder_python_imports
        rev: v2.6.0
        hooks:
            -   id: reorder-python-imports
